import logo from './logo.jpeg';
import profile from './profile.png'
export { logo,profile };

export const sessions = [
  {
    _id: "1",
    title: "Morning Yoga Flow",
    tags: ["yoga", "morning", "beginner"],
    description: "Start your day with this refreshing morning yoga sequence.",
    status: "published",
    json_file_url: "/files/morning-yoga.json",
    created_at: "2025-07-01",
    updated_at: "2025-07-10",
    user: { name: "Sujit" },
  },
  {
    _id: "2",
    title: "Deep Sleep Meditation",
    tags: ["meditation", "sleep", "relax"],
    description: "Guided meditation to help you fall asleep peacefully.",
    status: "published",
    json_file_url: "/files/sleep-meditation.json",
    created_at: "2025-06-20",
    updated_at: "2025-06-25",
    user: { name: "Aarav" },
  },
  {
    _id: "3",
    title: "Stress Relief Stretch",
    tags: ["stretch", "stress", "evening"],
    description: "Calm your body and mind with gentle stretches after a long day.",
    status: "published",
    json_file_url: "/files/stress-relief.json",
    created_at: "2025-07-05",
    updated_at: "2025-07-11",
    user: { name: "Diya" },
  },
  {
    _id: "4",
    title: "Focus Booster Meditation",
    tags: ["meditation", "focus", "productivity"],
    description: "A short meditation to improve your concentration during work.",
    status: "published",
    json_file_url: "/files/focus-boost.json",
    created_at: "2025-06-30",
    updated_at: "2025-07-03",
    user: { name: "Kabir" },
  },
  {
    _id: "5",
    title: "Full Body Workout",
    tags: ["workout", "fitness", "intermediate"],
    description: "A balanced workout to tone your entire body in 30 minutes.",
    status: "published",
    json_file_url: "/files/full-body.json",
    created_at: "2025-07-02",
    updated_at: "2025-07-04",
    user: { name: "Sujit" },
  },
  {
    _id: "6",
    title: "Guided Breathing Session",
    tags: ["breathing", "relaxation", "calm"],
    description: "Breathe mindfully and reduce anxiety in under 10 minutes.",
    status: "published",
    json_file_url: "/files/breathing.json",
    created_at: "2025-07-07",
    updated_at: "2025-07-09",
    user: { name: "Meera" },
  },
  {
    _id: "7",
    title: "Chair Yoga for Office",
    tags: ["yoga", "office", "sitting"],
    description: "Simple chair yoga poses you can do during work breaks.",
    status: "published",
    json_file_url: "/files/chair-yoga.json",
    created_at: "2025-07-03",
    updated_at: "2025-07-05",
    user: { name: "Ayaan" },
  },
  {
    _id: "8",
    title: "Bedtime Wind Down",
    tags: ["sleep", "night", "yoga"],
    description: "A soft yoga routine to prepare your body for restful sleep.",
    status: "published",
    json_file_url: "/files/bedtime.json",
    created_at: "2025-06-28",
    updated_at: "2025-07-01",
    user: { name: "Sujit" },
  },
  {
    _id: "9",
    title: "Quick Core Blast",
    tags: ["core", "workout", "intense"],
    description: "An intense 15-minute core workout to build strength.",
    status: "published",
    json_file_url: "/files/core-blast.json",
    created_at: "2025-07-08",
    updated_at: "2025-07-10",
    user: { name: "Riya" },
  },
  {
    _id: "10",
    title: "Gratitude Practice",
    tags: ["mindfulness", "gratitude", "daily"],
    description: "Take a moment to reflect and practice gratitude each morning.",
    status: "published",
    json_file_url: "/files/gratitude.json",
    created_at: "2025-07-09",
    updated_at: "2025-07-10",
    user: { name: "Sujit" },
  },
  {
    _id: "11",
    title: "Hip Mobility Flow",
    tags: ["mobility", "yoga", "hips"],
    description: "Loosen up tight hips and improve flexibility in just 20 minutes.",
    status: "published",
    json_file_url: "/files/hip-mobility.json",
    created_at: "2025-07-04",
    updated_at: "2025-07-06",
    user: { name: "Rohan" },
  },
  {
    _id: "12",
    title: "Digital Detox Meditation",
    tags: ["meditation", "detox", "relax"],
    description: "Step away from screens and refresh your mind with this session.",
    status: "published",
    json_file_url: "/files/detox.json",
    created_at: "2025-07-06",
    updated_at: "2025-07-07",
    user: { name: "Sujit" },
  },
  {
    _id: "13",
    title: "Sun Salutation Series",
    tags: ["sun", "yoga", "flow"],
    description: "A classic yoga sequence to energize your entire body.",
    status: "published",
    json_file_url: "/files/sun-salutation.json",
    created_at: "2025-06-25",
    updated_at: "2025-06-28",
    user: { name: "Diya" },
  }
];
